apiVersion: v1
kind: ConfigMap
metadata:
  name: extended-scheduler-kube-config
  namespace: default
data:
  scheduler.conf: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: redacted
        server: https://<api-server-ip>:<api-server-port>
      name: kubernetes
    contexts:
    - context:
        cluster: kubernetes
        user: system:kube-scheduler
      name: system:kube-scheduler@kubernetes
    current-context: system:kube-scheduler@kubernetes
    kind: Config
    preferences: {}
    users:
    - name: system:kube-scheduler
      user:
        client-certificate-data: redacted
        client-key-data: redacted